# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Web framework for PHP
email: yousaf@bmail.pk
description: >- # this means to ignore newlines until "baseurl:"
  Fast un-opinionated minimalist web framework and server for PHP built on top of battle tested Async PHP servers (SwoolePHP and ReactPHP).
  CrowPHP lets you build real microservices in PHP without the use of PHP-FPM/Nginx or Apache.
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc

url: crowphp.com
baseurl: /

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: nav flex-column
  sublist_class: ''
  item_class: nav-item nav-link
  item_prefix: toc-
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
